language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/3.3.gemfile
  - gemfiles/3.4.gemfile
before_install: gem install bundler -v 1.11.2
